version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    command: sh -c "knex migrate:latest --knexfile knexfile.js && yarn start"
    environment:
      - POSTGRES_DB=incidents
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - NODE_ENV=development
      - PORT=3003
    deploy:
       restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on: 
      - postgres
    volumes:
      - .:/usr/app
      
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=incidents
    user: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"    
    restart: always
volumes:
  database:
